[package]
name = "vko_tracer"
version = "0.1.0"
authors = ["ianmanor"]
build="build.rs"

[dependencies]
vulkano="0.7.2"

[badges]
travis-ci = { repository = "imvm/vko_tracer", branch = "master" }
codecov = { repository = "imvm/vko_tracer", branch = "master", service = "github" }