/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Raytracer */

#ifndef _Included_Raytracer
#define _Included_Raytracer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Raytracer
 * Method:    raytrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Raytracer_raytrace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
