/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VkoTracer */

#ifndef _Included_VkoTracer
#define _Included_VkoTracer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
